### ISSUE TITLE
Tooltip information incorrect

### ISSUE THREAD

**Issue by royemmerich** [NatelEnergy/grafana-discrete-panel#11]
I have two metrics in a single discrete panel. When mousing over I see the following:

![screen shot 2017-04-02 at 17 21 03](https://cloud.githubusercontent.com/assets/3904395/24588469/f9809eaa-17c8-11e7-8aa6-35dbbe3b2cff.png)

* The tooltip text only refers to the bottom metric, even though my mouse is over the top metric.
* The indicated time is rounded off to full days whereas I'd expect to see something like **3 days, 4 hours, 21 minutes, 47 seconds** or for brevity **3d, 4h, 21m, 47s**

**Comment by ryantxu** [comment]
That should already be fixed in master -- but not yet released

**Comment by royemmerich** [comment]
Unfortunately it looks like tooltips have stopped working in v0.03. They do still appear when hovering over the legend though.

**Comment by royemmerich** [comment]
For panels with two metrics, no tooltip is shown.

The data shown is still of the rounded up variety. In the image below it would be great to have the following shown in the tooltip:

```
no balancing
2017-04-20 16:06 to 2017-04-21 18:41:29 = 1d, 2h, 35m, 29s
```
<img width="243" alt="screen shot 2017-04-21 at 21 02 42" src="https://cloud.githubusercontent.com/assets/3904395/25292339/034e5550-26d6-11e7-95ba-e388826d2d58.png">
